# Generated by Django 4.0 on 2021-12-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_text_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Заголовокhui')),
                ('text', models.CharField(default='', max_length=256, verbose_name='Текстhui')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='isPinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
    ]
