# Generated by Django 4.0 on 2021-12-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_topic_post_ispinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='isPinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
    ]
