# Generated by Django 4.0 on 2021-12-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_ispinned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AlterField(
            model_name='post',
            name='isPinned',
            field=models.BooleanField(verbose_name='Закреплено'),
        ),
    ]
