# Generated by Django 4.0 on 2021-12-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_post_ispinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isPinned',
        ),
    ]
