# Generated by Django 4.0 on 2021-12-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_ispinned'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Note',
        ),
    ]
