# Generated by Django 4.0 on 2021-12-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_post_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='isPinned',
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(blank=True, max_length=256, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=32, verbose_name='Заголовок'),
        ),
    ]
