# Generated by Django 4.0 on 2021-12-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_note_ispinned_alter_note_id_alter_note_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='isPinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
    ]
