# Generated by Django 4.0 on 2021-12-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
